version: "3"

services:
  productfilter:
    container_name: productfilter
    build:
      context: ./.
      dockerfile: Dockerfile.dev
    networks:
      - default
    volumes:
      - "./.:/app/."
      - "/app/node_modules"
    ports:
      - "3000:3000"
    command: npm run dev
    
    environment:
      - DEBUG=1
      - NODE_ENV=development
      - PORT=3000
      - NEXT_PUBLIC_API_URI=